# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 问心居
email: ryuan3@usfca.edu
description: > # this means to ignore newlines until "baseurl:"
  A website used to study network knowledge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ruiling.me" # the base hostname & protocol for your site
twitter_username: doris0yuan
github_username:  ryuan3

# Build settings
markdown: kramdown
